Repository TecheerTeam/floe-frontend, pull requests merged in 2024-12, with the labels that each got.

#7 design: 대댓글 컴포넌트 수정
  src/app/globals.css
  src/app/post/detail/PostDetail.module.css
  src/app/post/detail/page.tsx
  src/components/comment/Comment.module.css
  src/components/comment/page.tsx
  src/components/reply/Reply.module.css
  src/components/reply/page.tsx
Labels: enhancement

#11 design: Auth 하위/ 자체 로그인 페이지 퍼블리싱완료
  src/app/auth/Auth.module.css
  src/app/auth/page.tsx
  src/app/auth/signin/Signin.module.css
  src/app/auth/signin/page.tsx
  src/app/auth/signup/Signup.module.css
  src/app/auth/signup/page.tsx
  src/app/globals.css
  src/app/onboard/page.tsx
  src/assets/ReturnIcon_Dark.png
  src/assets/ReturnIcon_Hover.png
  src/assets/ReturnIcon_White.png
Labels: enhancement

#13 design: Auth 하위 / 자체 회원가입 페이지 퍼블리싱 완료
  src/app/auth/signin/Signin.module.css
  src/app/auth/signup/Signup.module.css
  src/app/auth/signup/page.tsx
  src/app/globals.css
Labels: duplicate

#14 Design/#1
  src/app/globals.css
  src/app/mypage/MyPage.module.css
  src/app/mypage/page.tsx
  src/app/navBar/page.tsx
  src/assets/JJangGuWinter.png
  src/assets/settingBlack.png
  src/assets/settingWhite.png
  src/components/tab/tabContents/likeContents/Like.Contents.module.css
  src/components/tab/tabContents/likeContents/page.tsx
  src/components/tab/tabContents/postsContents/Posts.Contents.module.css
  src/components/tab/tabContents/postsContents/page.tsx
  src/components/tab/tabContents/saveContents/Save.Contents.module.css
  src/components/tab/tabContents/saveContents/page.tsx
  src/components/tab/tabNavigation/Tab.Navigation.module.css
  src/components/tab/tabNavigation/page.tsx
Labels: enhancement

#15 api 1차 추가
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/request/auth/index.ts
  src/apis/request/auth/sign-in.request.dto.ts
  src/apis/request/auth/sign-up.request.dto.ts
  src/apis/request/record/index.ts
  src/apis/request/record/record.request.dto.ts
  src/apis/request/user/index.ts
  src/apis/request/user/user.request.dto.ts
  src/apis/response/Response.dto.ts
  src/apis/response/auth/index.ts
  src/apis/response/auth/sign-in.response.dto.ts
  src/apis/response/auth/sign-up.response.dto.ts
  src/apis/response/index.ts
  src/apis/response/record/comment.response.dto.ts
  src/apis/response/record/favorite.response.dto.ts
  src/apis/response/record/index.ts
  src/apis/response/record/record.response.dto.ts
  src/apis/response/user/get-sign-in.user.response.dto.ts
  src/apis/response/user/get-user.response.dto.ts
  src/apis/response/user/index.ts
  src/apis/response/user/put-nickname.response.dto.ts
  src/apis/response/user/put-profile-image.response.dto.ts
  src/app/constant/route.ts
  src/types/enum/index.ts
  src/types/enum/response-code.enum.ts
  src/types/interface/comment-item.interface.ts
  src/types/interface/favorite-item.interface.ts
  src/types/interface/index.ts
  src/types/interface/record-item.interface.ts
  src/types/interface/user.interface.ts
Labels: enhancement

#18 게시물,댓글,좋아요 dto 추가 / 백엔드측 최신화 끝나면 리팩토링 필요
  src/apis/index.ts
  src/apis/request/record/record.request.dto.ts
  src/apis/response/Response.dto.ts
  src/apis/response/record/comment.response.dto.ts
  src/apis/response/record/favorite.response.dto.ts
  src/apis/response/record/index.ts
  src/apis/response/record/like.response.dto.ts
  src/apis/response/record/record.response.dto.ts
  src/app/post/write/page.tsx
  src/types/enum/response-code.enum.ts
  src/types/interface/comment-item.interface.ts
  src/types/interface/index.ts
  src/types/interface/like-item.interface.ts
  src/types/interface/record-item.interface.ts
Labels: enhancement

#21 api 3차 추가 및 수정, 댓글,로그인 부분 미구현
  src/apis/index.ts
  src/apis/request/record/record.request.dto.ts
  src/apis/response/record/like.response.dto.ts
  src/types/interface/record-item.interface.ts
Labels: enhancement

#26 Feat/#22
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/response/record/record.response.dto.ts
  src/app/Home.module.css
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/home/Home.module.css
  src/app/home/Main.tsx
  src/app/home/page.tsx
  src/app/hooks/useInfiniteRecords.tsx
  src/app/layout.tsx
  src/app/mock/mockComment.ts
  src/app/mock/mockLike.ts
  src/app/mock/mockRecord.ts
  src/app/mock/mockRecordList.ts
  src/app/page.tsx
  src/components/home/MainContent.tsx
  src/components/post/postItemCardType/page.tsx
  src/lib/QueryProvider.tsx
  src/store/index.ts
  src/store/login-user.store.ts
  src/store/record-type.store.ts
  src/store/record.store.ts
  src/types/interface/index.ts
Labels: duplicate, enhancement

#28 fix: withCredentials: true 추가
  src/apis/index.ts
Labels: bug

#31 fix: withCredentials: true 삭제
  src/apis/index.ts
Labels: bug

#34 main page 게시물 데이터 fetching 오류 해결
  package-lock.json
  src/app/home/Main.tsx
Labels: bug

#38 feat: Post Write 페이지 event handler 추가
  src/app/post/write/PostWrite.module.css
  src/app/post/write/page.tsx
  src/store/record.store.ts
Labels: enhancement

#41 로그인,회원가입 연동 완료(로그인 에러 이슈로 인해 추후 재수정 필요)
  src/apis/index.ts
  src/apis/request/auth/sign-in.request.dto.ts
  src/apis/request/auth/sign-up.request.dto.ts
  src/apis/response/auth/sign-in.response.dto.ts
  src/app/auth/signin/page.tsx
  src/app/auth/signup/Signup.module.css
  src/app/auth/signup/page.tsx
  src/app/home/Main.tsx
  src/app/layout.tsx
  src/store/index.ts
  src/store/login-user.store.ts
  src/types/enum/response-code.enum.ts
  src/types/interface/user.interface.ts
Labels: enhancement

#43 fix: sign-in resposne data = null 인 오류 수정 및 resposne header에서 accessT…
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/image.png
  src/apis/index.ts
  src/apis/response/auth/index.ts
  src/apis/response/auth/sign-in.response.dto.ts
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
Labels: bug

#44 record api 수정필요
  src/apis/index.ts
  src/apis/response/record/record.response.dto.ts
  src/apis/response/user/get-sign-in.user.response.dto.ts
  src/apis/response/user/index.ts
  src/app/auth/signin/page.tsx
  src/app/layout.tsx
  src/app/navBar/page.tsx
  src/app/post/[recordId]/page.tsx
  src/app/post/write/page.tsx
Labels: enhancement

#46 fix: record api 오류 수정(db 테이블 충돌로 인한 오류), main 및 detail page 게시물 연동 완료
  src/apis/index.ts
  src/apis/response/record/record.response.dto.ts
  src/app/auth/signin/page.tsx
  src/app/home/Main.tsx
  src/app/layout.tsx
  src/app/navBar/page.tsx
  src/app/post/[recordId]/page.tsx
  src/app/post/write/page.tsx
  src/store/login-user.store.ts
  src/types/interface/record-item.interface.ts
  src/types/interface/record-list-item.interface.ts
Labels: bug

#48 feat: 로그인 여부에 따른 mypage 이동 수정완료, 로그인 유저 상태 연결 완료
  src/apis/index.ts
  src/apis/request/record/record.request.dto.ts
  src/app/home/Main.tsx
  src/app/layout.tsx
  src/app/mypage/MyPage.module.css
  src/app/mypage/page.tsx
  src/app/navBar/page.tsx
  src/app/post/[recordId]/page.tsx
  src/app/post/write/page.tsx
  src/components/comment/page.tsx
  src/components/tab/tabContents/likeContents/page.tsx
  src/components/tab/tabContents/postsContents/page.tsx
  src/components/tab/tabContents/saveContents/page.tsx
Labels: enhancement
